- name: install pip3
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: install docker python modules
  pip:
    name:
      - docker
      - docker-compose

- name: run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports:
      - "8081:8080"
    state: started
 
